ru.vachok.networker.net.DiapazonedScan
srvFiles - NOT final; srvFiles .streams; copy srvfiles by Vlans1010ToScan

ru.vachok.networker.net.DiapazonedScan.Vlans1010ToScan;
message, when run; method .cpFile()

ru.vachok.networker.ExitApp#copyAvail
srvFiles.stream()

ru.vachok.networker.net.NetListKeeper#readMap
ConcurrentMap weaken and renamed : fromFileMap

ru.vachok.networker.net.NetScanFileWorker#getListOfOnlineDev
if (srvFiles != null) {

ru.vachok.networker.net.ScanOnline#runPing
delete readmap()

ru.vachok.networker.ExitApp#run
commitfile

ru.vachok.networker.net.ScanOnline#offlineNotEmptyActions
Future<?> submit

ru.vachok.networker.fileworks.FileSystemWorker
remove SYNC

ru.vachok.networker.config.ThreadConfig.TaskDestroyer.rejectedExecution
executor.purge();

ru.vachok.networker.net.MyServer.printToSocket
threads info on start